### ISSUE TITLE
Undefined subroutine 

### ISSUE THREAD

**Issue by brestows** [drmuey/p5-Dancer2-Plugin-Locale#4]
Hi! 
when I try to use this plugin, I get this error:
`Error while loading /home/devcode/Project/adminpanel/bin/app.psgi: Undefined subroutine &Dancer2::Plugin::Locale::from_json called at /usr/share/perl5/site_perl/Dancer2/Plugin/Locale.pm line 97, <$fh> line 1.`

What is this about?

**Comment by drmuey** [comment]
@brestows A change to Dancer2 required this change that I will try to get out ASAP

```
 sub _from_json_file {
     my ($file) = @_;
     open( my $fh, '<', $file ) or die "Could not read “$file”: $!";
-    use Dancer2::Serializer::JSON;
-    return Dancer2::Serializer::JSON::from_json(
+    return from_json(
         do { local $/; <$fh> }
     );
 }
```

**Comment by brestows** [comment]
Sorry, I don't understand how the function should look like _from_json_file    and now it looks like

`sub _from_json_file {
    my ($file) = @_;
    open( my $fh, '<', $file ) or die "Could not read “$file”: $!";
    return from_json(
        do { local $/; <$fh> }
    );
}`

 and I get this error. Thank you

**Comment by drmuey** [comment]
Sorry, the diff was backwards :)

```
 sub _from_json_file {
     my ($file) = @_;
     open( my $fh, '<', $file ) or die "Could not read “$file”: $!";
+    use Dancer2::Serializer::JSON;
+    return Dancer2::Serializer::JSON::from_json(
-    return from_json(
         do { local $/; <$fh> }
     );
 }
```

meaning the final version should look like:

```
 sub _from_json_file {
     my ($file) = @_;
     open( my $fh, '<', $file ) or die "Could not read “$file”: $!";
     use Dancer2::Serializer::JSON;
     return Dancer2::Serializer::JSON::from_json(
         do { local $/; <$fh> }
     );
 }
```

I'll try to get a release out ASAP w/ that change, thanks!

**Comment by brestows** [comment]
I thought so :) But unfortunately it did not help
`
File is /home/devcode/Project/adminpanel/locale/en.json      in /home/devcode/Project/adminpanel/locale  at /usr/share/perl5/site_perl/Dancer2/Plugin/Locale.pm line 70.
Error while loading /home/devcode/Project/adminpanel/bin/app.psgi: Can't use string ("Dancer2::Serializer::JSON") as a HASH ref while "strict refs" in use at (eval 272) line 18, <$fh> line 1.
`

**Comment by drmuey** [comment]
hmmm, can you post the entire `_from_json_file`?

**Comment by brestows** [comment]
```
sub _from_json_file {
    my ($file)  = @_;
     open( my $fh, '<', $file ) or die "Could not read "$file": $!";
     use Dancer2::Serializer::JSON;
     return Dancer2::Serializer::JSON::from_json(
            do { local $/; <$fh> }
     );
 }
```

**Comment by brestows** [comment]
Hello. Is there any information about this error? Thank you

**Comment by drmuey** [comment]
Sorry for the delay! I will attend to this by Tuesday evening, thanks!

**Comment by brestows** [comment]
thanks!

**Comment by drmuey** [comment]
Sorry for the delay!

I am using v 0.05 successfully w/ Dancer2 v0.204000.

Do you still experience this problem w/ the latest version of both?

I ask because I suspect it may be disconnect from the Dancer2 plugin refactor where one is old and one is new.

**Comment by brestows** [comment]
I installed dancer2 v 0.201000, try to upgrade to 0,204000.  
I write results

**Comment by brestows** [comment]
Show me please example of the json file translate, I add file en.json:
```
'Sign In':'SIGN IN'
```
and get error:
```
[devcode@TuxBook]>>plackup -R ../lib,../config.yml,../views                
Watching ../lib ../config.yml ../views ./lib app.psgi for file updates.
Error while loading /home/devcode/Project/Web-App/bin/app.psgi: Can't use string ("Dancer2::Serializer::JSON") as a HASH ref while "strict refs" in use at (eval 248) line 18, <$fh> line 1.
BEGIN failed--compilation aborted at /home/devcode/Project/Web-App/bin/../lib/Web/App.pm line 3.
Compilation failed in require at /home/devcode/Project/Web-App/bin/app.psgi line 8.
BEGIN failed--compilation aborted at /home/devcode/Project/Web-App/bin/app.psgi line 8
```
If add empty file en.json, i don't get error.

**Comment by drmuey** [comment]
It looks like you still have a patched version of it, make sure its the same exact version as what is on CPAN.

Meantime here is a simple test lexicon form French:

e.g. locale/fr.json

```
"Hello World" : "Bonjour Monde",
"A password is required." : "Un mot de passe est requis."
```

**Comment by brestows** [comment]
I don't know what to do (
```
[devcode@TuxBook]>>sudo cpanm --reinstall Dancer2::Plugin::Locale                                                        ~/ :)
zsh: correct 'cpanm' to '.cpanm' [nyae]? n
--> Working on Dancer2::Plugin::Locale
Fetching http://www.cpan.org/authors/id/D/DM/DMUEY/Dancer2-Plugin-Locale-0.05.tar.gz ... OK
Configuring Dancer2-Plugin-Locale-0.05 ... OK
Building and testing Dancer2-Plugin-Locale-0.05 ... OK
Successfully reinstalled Dancer2-Plugin-Locale-0.05
1 distribution installed
[devcode@TuxBook]>>dancer2 -v                                                                                                     
Dancer2 0.204001
[devcode@TuxBook]>>cd Project                                                                                            ~/ :)
[devcode@TuxBook]>>dancer2 -a MyApplication   
```
Add line in lib/MyApplication.pm
```
use Dancer2::Plugin::Locale;
```
```
mkdir public/locale
touch public/locale/en.json
ln -s public/locale locale
```
Insert "Sign In":"SIGN IN" to public/locale/en.json

run app and get error:

```[devcode@TuxBook]>>     plackup -R ../lib,../config.yml,../views    
Watching ../lib ../config.yml ../views ./lib app.psgi for file updates.
Error while loading /home/devcode/Project/MyApplication/bin/app.psgi: Undefined subroutine &Dancer2::Plugin::Locale::from_json called at /usr/share/perl5/site_perl/Dancer2/Plugin/Locale.pm line 97.
BEGIN failed--compilation aborted at /home/devcode/Project/MyApplication/bin/../lib/MyApplication.pm line 3.
Compilation failed in require at /home/devcode/Project/MyApplication/bin/app.psgi line 8.
BEGIN failed--compilation aborted at /home/devcode/Project/MyApplication/bin/app.psgi line 8.

```

**Comment by drmuey** [comment]
`rm /usr/share/perl5/site_perl/Dancer2/Plugin/Locale.pm` first, I suspect the cpan command is installing the new one somewhere else or not overwriting it but that is the one being used which appears to be patched (due to the error)

**Comment by drmuey** [comment]
sorry, phat finger :)

**Comment by brestows** [comment]
It's my Locale.pm after reinstall

https://hastebin.com/hiqeziwisa.pl

**Comment by drmuey** [comment]
ah! thanks I think I see it now, my test was using a patched one, sorry I didn't notice that sooner.

let me look a bit further and get back to you, sorry!

**Comment by brestows** [comment]
No problem )

**Comment by drmuey** [comment]
ok, yeah the original patch does need applied, apologies that I overlooked my local patched copy! Will try to have that tonight.

Also, I may have been unclear earlier but the JSON does need to be a hash; so:

```
{
    … : …,
    … : …
}
```
instead of 

```
… : …,
… : …
```

**Comment by brestows** [comment]
Thanks, I am waiting fix )

**Comment by drmuey** [comment]
v0.06 as uploaded to CPAN w/ the fix, thanks!
